package httpapi_test

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/ThalesMMS/CodeAtlas/internal/capabilities"
	"github.com/ThalesMMS/CodeAtlas/internal/domain"
	"github.com/ThalesMMS/CodeAtlas/internal/httpapi"
	"github.com/ThalesMMS/CodeAtlas/internal/indexer"
	codeparser "github.com/ThalesMMS/CodeAtlas/internal/parser"
	"github.com/ThalesMMS/CodeAtlas/internal/readiness"
	"github.com/ThalesMMS/CodeAtlas/internal/repository"
	"github.com/ThalesMMS/CodeAtlas/internal/retrieval"
	"github.com/ThalesMMS/CodeAtlas/internal/service"
	"github.com/ThalesMMS/CodeAtlas/internal/webui"
)

func TestServerFeatureFlow(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFixture(t, root, "web/checkout.ts", `export class Checkout {
  completeCheckout() { submitOrder() }
}
function submitOrder() {}
`)
	writeFixture(t, root, "internal/order/service.go", `package order

type Service struct{}
func (s *Service) Submit() { Save() }
func Save() {}
`)

	repository, err := repository.OpenSQLite(context.Background(), repository.SQLiteConfig{WorkspaceRoot: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = repository.Close() })
	provider := staticProvider{response: "## Response generated by the LLM"}
	retriever := retrieval.NewHybrid(repository, provider, false)
	backgroundIndexer := indexer.New(root, 1_500_000, codeparser.New(), repository, retriever)
	if err := backgroundIndexer.Scan(context.Background()); err != nil {
		t.Fatalf("Scan() error = %v", err)
	}
	workspace := service.NewWorkspace(root)
	explainer := service.NewExplainer(repository, workspace, provider)
	codemaps := service.NewCodemapService(repository, retriever, provider)
	deepWiki := service.NewDeepWikiService(repository, provider)
	if _, err := deepWiki.Generate(context.Background()); err != nil {
		t.Fatalf("Generate DeepWiki error = %v", err)
	}
	saver := service.NewSavePreparer(workspace, repository, codeparser.New(), retriever, 1_500_000)
	committer := service.NewWorkspaceCommitCoordinator(saver, workspace, repository, filepath.Join(t.TempDir(), "tx"), "")
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	server := httptest.NewServer(httpapi.New(
		workspace, repository, backgroundIndexer, retriever, explainer, codemaps, deepWiki, committer, provider,
		coordinatorInState(t, readiness.StateReady), capabilities.NewRegistry(), logger,
	).Handler())
	defer server.Close()

	var stats domain.WorkspaceStats
	getJSON(t, server.URL+"/api/stats", &stats)
	if stats.Files != 2 || stats.Symbols < 6 || stats.WikiPages == 0 {
		t.Fatalf("unexpected stats: %#v", stats)
	}

	var explanation domain.Explanation
	postJSON(t, server.URL+"/api/explain", domain.ExplainRequest{
		Feature: domain.ExplainFeatureHover,
		Path:    "web/checkout.ts",
		Position: &domain.Position{
			Line: 2, Column: 8, Encoding: "utf-16",
		},
	}, &explanation)
	if explanation.Symbol.Name != "completeCheckout" || len(explanation.Evidence) == 0 {
		t.Fatalf("unexpected explanation: %#v", explanation)
	}
	if explanation.Feature != domain.ExplainFeatureHover || explanation.Result.SchemaVersion != "explanation/v2" || explanation.Result.Summary == "" {
		t.Fatalf("missing structured explanation result: %#v", explanation)
	}
	if explanation.Evidence[0].ID == "" || explanation.Evidence[0].OccurrenceID == "" {
		t.Fatalf("evidence must expose validated IDs: %#v", explanation.Evidence[0])
	}
	if explanation.PromptVersion != "hover-v3" || explanation.ProviderInfo.ID != provider.Name() {
		t.Fatalf("missing prompt/provider metadata: prompt=%q providerInfo=%#v", explanation.PromptVersion, explanation.ProviderInfo)
	}
	if explanation.Provider != provider.Name() || explanation.Markdown != provider.response {
		t.Fatalf("unexpected explanation provider/markdown: %#v", explanation)
	}

	var codemapRef struct {
		Job domain.JobSnapshot `json:"job"`
	}
	postJSONStatus(t, server.URL+"/api/codemaps", domain.CodemapRequest{
		Query: "checkout submit service save", MaxNodes: 12,
	}, http.StatusAccepted, &codemapRef)
	waitHTTPJob(t, server.URL, codemapRef.Job.ID, domain.JobSucceeded)
	var codemap domain.Codemap
	getJSON(t, server.URL+"/api/jobs/"+string(codemapRef.Job.ID)+"/result", &codemap)
	if len(codemap.Nodes) < 4 || len(codemap.Nodes) > 12 || len(codemap.Edges) == 0 {
		t.Fatalf("unexpected codemap size: nodes=%d edges=%d", len(codemap.Nodes), len(codemap.Edges))
	}
	if codemap.Provider != provider.Name() || codemap.Overview != provider.response {
		t.Fatalf("unexpected codemap provider/overview: %#v", codemap)
	}
	var restored domain.Codemap
	getJSON(t, server.URL+"/api/codemaps/"+url.PathEscape(string(codemap.Artifact.ID)), &restored)
	if restored.Artifact.ID != codemap.Artifact.ID || restored.Title != codemap.Title || restored.Artifact.Status != domain.ArtifactCurrent {
		t.Fatalf("restored codemap = %#v, want artifact %q", restored, codemap.Artifact.ID)
	}

	request, err := http.NewRequest(http.MethodGet, server.URL+"/api/file?path=..%2Fsecret.go", nil)
	if err != nil {
		t.Fatal(err)
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		t.Fatal(err)
	}
	response.Body.Close()
	if response.StatusCode != http.StatusBadRequest {
		t.Fatalf("traversal status = %d, want 400", response.StatusCode)
	}
}

func TestStatsExposeFrontendManifest(t *testing.T) {
	t.Parallel()
	server := healthServer(t, coordinatorInState(t, readiness.StateReady), capabilities.NewRegistry())

	var body struct {
		Frontend webui.BuildManifest `json:"frontend"`
	}
	getJSON(t, server.URL+"/api/stats", &body)

	if body.Frontend.Editor != "monaco" || body.Frontend.EditorVersion != "0.53.0" || body.Frontend.BuildVersion == "" {
		t.Fatalf("frontend manifest = %#v, want Monaco editor metadata", body.Frontend)
	}
}

type staticProvider struct {
	response string
}

func (p staticProvider) Name() string { return "static-llm" }

func (p staticProvider) Available() bool { return true }

func (p staticProvider) Complete(_ context.Context, systemPrompt, _ string, _ int) (string, error) {
	if p.response == "" {
		return "", errors.New("empty test response")
	}
	// A structured Explanation request gets a minimal grounded object (summary
	// only, no cited evidence) so the grounding validator accepts it; the summary
	// carries the configured response for the feature-flow assertion.
	if strings.Contains(systemPrompt, "explanation/v2") {
		return `{"schemaVersion":"explanation/v2","summary":` + strconv.Quote(p.response) + `,"observations":[],"inferences":[],"uncertainties":[],"changeImpact":[]}`, nil
	}
	if strings.Contains(systemPrompt, "codemap-narrative/v2") {
		return `{"schemaVersion":"codemap-narrative/v2","title":"Map","overview":` + strconv.Quote(p.response) + `,"motivation":"","details":"","trace":[],"flows":[],"claims":[],"inferences":[],"uncertainties":[]}`, nil
	}
	if strings.Contains(systemPrompt, "wiki-page/v4") {
		return `{"schemaVersion":"wiki-page/v4","title":` + strconv.Quote(p.response) + `,"sections":[{"heading":` + strconv.Quote(p.response) + `,"claims":[]}],"relatedPages":[],"inferences":[],"limitations":[]}`, nil
	}
	return p.response, nil
}

func (p staticProvider) Embed(context.Context, []string) ([][]float64, error) {
	return nil, errors.New("embeddings disabled in test")
}

func writeFixture(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func getJSON(t *testing.T, url string, target any) {
	t.Helper()
	response, err := http.Get(url)
	if err != nil {
		t.Fatal(err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(response.Body)
		t.Fatalf("GET %s status=%d body=%s", url, response.StatusCode, body)
	}
	if err := json.NewDecoder(response.Body).Decode(target); err != nil {
		t.Fatal(err)
	}
}

func postJSON(t *testing.T, url string, payload, target any) {
	t.Helper()
	body, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}
	response, err := http.Post(url, "application/json", bytes.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		data, _ := io.ReadAll(response.Body)
		t.Fatalf("POST %s status=%d body=%s", url, response.StatusCode, data)
	}
	if err := json.NewDecoder(response.Body).Decode(target); err != nil {
		t.Fatal(err)
	}
}
