package service

import (
	"context"
	"encoding/json"
	"errors"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/ThalesMMS/CodeAtlas/internal/ai"
	"github.com/ThalesMMS/CodeAtlas/internal/aiout"
	"github.com/ThalesMMS/CodeAtlas/internal/apperror"
	"github.com/ThalesMMS/CodeAtlas/internal/domain"
	codeparser "github.com/ThalesMMS/CodeAtlas/internal/parser"
	"github.com/ThalesMMS/CodeAtlas/internal/repository"
	"github.com/ThalesMMS/CodeAtlas/internal/retrieval"
)

type countingSnapshotStore struct {
	repository.Store
	snapshots int
}

func (s *countingSnapshotStore) Snapshot() repository.ReadView {
	s.snapshots++
	return s.Store.Snapshot()
}
func (s *countingSnapshotStore) SnapshotContext(ctx context.Context) (repository.ReadView, error) {
	s.snapshots++
	return s.Store.SnapshotContext(ctx)
}

func TestCodemapHonorsNodeBudgetAndKeepsValidEdges(t *testing.T) {
	t.Parallel()
	repository, err := repository.OpenSQLite(context.Background(), repository.SQLiteConfig{WorkspaceRoot: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = repository.Close() })
	engine := codeparser.New()
	indexSource(t, repository, engine, "internal/order/service.go", `package order

type Service struct{}
func (s *Service) Submit() { validateOrder(); Save() }
func validateOrder() {}
func Save() {}
`)
	indexSource(t, repository, engine, "web/checkout.ts", `export class Checkout {
  completeCheckout() { submitOrder() }
}
function submitOrder() {}
`)

	provider := &capturingProvider{response: "## Map generated by the LLM"}
	countingStore := &countingSnapshotStore{Store: repository}
	retriever := retrieval.NewHybrid(countingStore, ai.Disabled{}, false)
	service := NewCodemapService(countingStore, retriever, provider)
	result, err := service.Generate(context.Background(), domain.CodemapRequest{
		Query:    "checkout submit order service save",
		MaxNodes: 8,
	})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(result.Nodes) > 8 {
		t.Fatalf("Generate() returned %d nodes, budget is 8", len(result.Nodes))
	}
	if result.Provider != provider.Name() {
		t.Fatalf("provider = %q, want %q", result.Provider, provider.Name())
	}
	if countingStore.snapshots != 1 {
		t.Fatalf("Codemap Snapshot calls = %d, want one pinned view", countingStore.snapshots)
	}
	nodeIDs := make(map[string]struct{}, len(result.Nodes))
	for _, node := range result.Nodes {
		nodeIDs[node.ID] = struct{}{}
	}
	for _, edge := range result.Edges {
		if _, ok := nodeIDs[edge.Source]; !ok {
			t.Fatalf("edge source %q has no node", edge.Source)
		}
		if _, ok := nodeIDs[edge.Target]; !ok {
			t.Fatalf("edge target %q has no node", edge.Target)
		}
	}
}

func TestCodemapRequestsExpandedOutputTokenBudget(t *testing.T) {
	t.Parallel()
	store, err := repository.OpenSQLite(context.Background(), repository.SQLiteConfig{WorkspaceRoot: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = store.Close() })
	engine := codeparser.New()
	indexSource(t, store, engine, "internal/order/service.go", `package order

type Service struct{}
func (s *Service) Submit() { Save() }
func Save() {}
`)

	provider := &capturingProvider{response: "Grounded map"}
	retriever := retrieval.NewHybrid(store, ai.Disabled{}, false)
	service := NewCodemapService(store, retriever, provider)
	if _, err := service.Generate(context.Background(), domain.CodemapRequest{
		Query:    "submit service save",
		MaxNodes: 8,
	}); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if provider.maxTokens != 12_288 {
		t.Fatalf("Codemap output token budget = %d, want 12288", provider.maxTokens)
	}
}

func TestCodemapReturnsProviderErrorInsteadOfHeuristicOverview(t *testing.T) {
	t.Parallel()
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = repository.Close() })
	engine := codeparser.New()
	indexSource(t, repository, engine, "internal/order/service.go", `package order

type Service struct{}
func (s *Service) Submit() { Save() }
func Save() {}
`)

	provider := &capturingProvider{err: errors.New("LLM endpoint unavailable")}
	retriever := retrieval.NewHybrid(repository, ai.Disabled{}, false)
	service := NewCodemapService(repository, retriever, provider)
	_, err = service.Generate(context.Background(), domain.CodemapRequest{
		Query:    "submit service save",
		MaxNodes: 8,
	})
	if err == nil {
		t.Fatal("Generate() succeeded with a failing provider; want error")
	}
	appErr, ok := apperror.As(err)
	if !ok || appErr.Code != apperror.CodeProviderUnavailable {
		t.Fatalf("error = %v, want PROVIDER_UNAVAILABLE app error", err)
	}
	if appErr.Cause == nil || !strings.Contains(appErr.Cause.Error(), "LLM endpoint unavailable") {
		t.Fatalf("provider cause not preserved: %v", appErr.Cause)
	}
}

func TestCodemapCanRecoverOnThirdGroundingAttempt(t *testing.T) {
	t.Parallel()
	store, err := repository.OpenSQLite(context.Background(), repository.SQLiteConfig{WorkspaceRoot: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = store.Close() })
	engine := codeparser.New()
	indexSource(t, store, engine, "internal/order/service.go", `package order

type Service struct{}
func (s *Service) Submit() { Save() }
func Save() {}
`)

	valid := structuredStub(codemapSystemPrompt, "Grounded map")
	provider := &scriptedProvider{responses: []string{`{}`, `{}`, valid}}
	retriever := retrieval.NewHybrid(store, ai.Disabled{}, false)
	service := NewCodemapService(store, retriever, provider)
	if _, err := service.Generate(context.Background(), domain.CodemapRequest{
		Query: "submit service save", MaxNodes: 8,
	}); err != nil {
		t.Fatalf("Generate() error = %v, want recovery on third grounded response", err)
	}
	if provider.calls != 3 {
		t.Fatalf("provider calls = %d, want 3", provider.calls)
	}
}

func TestCodemapProviderPromptIncludesFlowGuideEvidence(t *testing.T) {
	t.Parallel()
	repository, err := repository.OpenSQLite(context.Background(), repository.SQLiteConfig{WorkspaceRoot: t.TempDir()})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = repository.Close() })
	engine := codeparser.New()
	indexSource(t, repository, engine, "cmd/api/main.go", `package main

import (
	"log"
	"net/http"

	"example.com/tinycommerce/internal/order"
)

func main() {
	repository := order.NewMemoryRepository()
	service := order.NewService(repository)
	handler := order.NewHandler(service)

	mux := http.NewServeMux()
	mux.HandleFunc("POST /orders", handler.Create)
	log.Fatal(http.ListenAndServe("127.0.0.1:8090", mux))
}
`)
	indexSource(t, repository, engine, "internal/order/http.go", `package order

import (
	"encoding/json"
	"net/http"
)

type Handler struct {
	service *Service
}

func NewHandler(service *Service) *Handler {
	return &Handler{service: service}
}

func (h *Handler) Create(response http.ResponseWriter, request *http.Request) {
	var input Order
	if err := json.NewDecoder(request.Body).Decode(&input); err != nil {
		http.Error(response, "invalid payload", http.StatusBadRequest)
		return
	}
	if err := h.service.Submit(request.Context(), input); err != nil {
		http.Error(response, err.Error(), http.StatusUnprocessableEntity)
		return
	}
	response.WriteHeader(http.StatusCreated)
}
`)
	indexSource(t, repository, engine, "internal/order/service.go", `package order

import (
	"context"
	"errors"
	"time"
)

type Service struct {
	repository Repository
	clock func() time.Time
}

func NewService(repository Repository) *Service {
	return &Service{repository: repository, clock: time.Now}
}

func (s *Service) Submit(ctx context.Context, order Order) error {
	if err := validateOrder(order); err != nil {
		return err
	}
	order.CreatedAt = s.clock().UTC()
	return s.repository.Save(ctx, order)
}

func validateOrder(order Order) error {
	return errors.New("invalid order")
}
`)
	indexSource(t, repository, engine, "internal/order/repository.go", `package order

import "context"

type Repository interface {
	Save(ctx context.Context, order Order) error
}

type MemoryRepository struct {
	orders map[string]Order
}

func NewMemoryRepository() *MemoryRepository {
	return &MemoryRepository{orders: make(map[string]Order)}
}

func (r *MemoryRepository) Save(_ context.Context, order Order) error {
	r.orders[order.ID] = order
	return nil
}
`)

	ids := make(map[string]string)
	for _, symbol := range repository.AllSymbols() {
		ids[symbol.Name] = symbol.ID
	}
	narrative := aiout.CodemapNarrative{
		SchemaVersion: aiout.CodemapSchemaVersion,
		Title:         "Handler in the HTTP flow",
		Overview:      strings.Repeat("The order handler connects dependency setup to validated request processing and persistence. ", 2),
		Motivation:    strings.Repeat("The application separates HTTP transport, business validation, and repository access so each layer owns one observable responsibility. ", 2),
		Details:       strings.Repeat("The entrypoint creates the repository, injects it into the service, and gives that service to the HTTP handler. The request path decodes the payload, delegates validation to Submit, timestamps the order, and saves it through the repository interface. ", 2),
		Flows: []aiout.CodemapFlow{
			{
				Title: "Configuration", EntryNodeID: ids["main"],
				Summary:    "Wires the repository, service, and handler.",
				Motivation: "The entrypoint has to assemble the dependency chain before any request arrives, so each layer receives its collaborator explicitly.",
				Details:    "The main function creates the repository [1b], injects it into the service [1c], and hands that service to the HTTP handler [1d] so transport code never touches storage directly.",
				Steps: []aiout.CodemapFlowStep{
					{Label: "1a", NodeID: ids["main"], Text: "Inicia o wiring"},
					{Label: "1b", NodeID: ids["NewMemoryRepository"], Text: "Cria o repository"},
					{Label: "1c", NodeID: ids["NewService"], Text: "Injeta o service"},
					{Label: "1d", NodeID: ids["NewHandler"], Text: "Builds the handler"},
				},
			},
			{
				Title: "Request processing", EntryNodeID: ids["Create"],
				Summary:    "Decodes, validates, and persists an order.",
				Motivation: "The request path must reject malformed and invalid orders before persistence so the repository only ever stores validated entities.",
				Details:    "The handler decodes the payload [2a], the service validates and timestamps the order [2b], and the repository stores it under its ID [2c], keeping HTTP concerns out of the storage layer.",
				Steps: []aiout.CodemapFlowStep{
					{Label: "2a", NodeID: ids["Create"], Text: "Decodes the request"},
					{
						Label: "2b", NodeID: ids["Submit"], Text: "Validates and submits the order",
						AnchorText: "order.CreatedAt = s.clock().UTC()",
						Notes:      []string{"validate before persisting", "stamp UTC creation time"},
					},
					{Label: "2c", NodeID: ids["Save"], Text: "Persists the order"},
				},
			},
		},
	}
	rawNarrative, err := json.Marshal(narrative)
	if err != nil {
		t.Fatal(err)
	}
	provider := &capturingProvider{structured: string(rawNarrative)}
	retriever := retrieval.NewHybrid(repository, ai.Disabled{}, false)
	service := NewCodemapService(repository, retriever, provider)
	result, err := service.Generate(context.Background(), domain.CodemapRequest{
		Query:    "What is the handler's role in the main function?",
		MaxNodes: 36,
	})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if result.Provider != provider.Name() {
		t.Fatalf("provider = %q, want %q", result.Provider, provider.Name())
	}
	for _, guidance := range []string{"40-90 words", "80-150 words", "150-350 words", "specific action and consequence", "anchorText", "4-8 steps per flow", "### "} {
		assertContains(t, provider.systemPrompt, guidance)
	}
	if strings.Contains(provider.systemPrompt, "short \"text\"") || strings.Contains(provider.systemPrompt, "Be concise") {
		t.Fatalf("Codemap prompt still asks for sparse prose:\n%s", provider.systemPrompt)
	}
	if result.OutputSchemaVersion != "codemap-narrative/v2" {
		t.Fatalf("output schema = %q, want codemap-narrative/v2", result.OutputSchemaVersion)
	}
	if result.Diagram == nil || result.Diagram.Version != "mermaid/v1" || result.Diagram.Kind != "flowchart" {
		t.Fatalf("deterministic diagram metadata = %+v", result.Diagram)
	}
	for _, label := range []string{"main", "NewHandler", "NewService", "NewMemoryRepository", "Create", "Submit", "Save"} {
		if !strings.Contains(result.Diagram.Source, label) {
			t.Fatalf("diagram missing %q:\n%s", label, result.Diagram.Source)
		}
	}
	if len(result.Diagram.Sources) == 0 {
		t.Fatalf("diagram has no navigable sources: %+v", result.Diagram)
	}
	// The model receives the factual graph (ref = path:line, with snippets) as data,
	// not a free-form guide; it narrates citing the provided IDs.
	assertContains(t, provider.userPrompt, "CODEATLAS_CODEMAP_STRUCTURE")
	assertContains(t, provider.userPrompt, `"ref":"cmd/api/main.go:10"`)
	assertContains(t, provider.userPrompt, `mux.HandleFunc(\"POST /orders\", handler.Create)`)
	assertContains(t, provider.userPrompt, `h.service.Submit(request.Context(), input)`)
	assertContains(t, provider.userPrompt, `"suggestedFlows"`)
	assertContains(t, provider.userPrompt, `"title":"Configuration"`)
	assertContains(t, provider.userPrompt, `"title":"Request processing"`)
	if strings.Contains(provider.userPrompt, "graph TD") || strings.Contains(provider.systemPrompt, "mermaid") {
		t.Fatal("deterministic diagram leaked into the model request")
	}
	if len(result.Flows) != 2 {
		t.Fatalf("flows = %+v, want main wiring and request processing", result.Flows)
	}
	if step := result.Flows[0].Steps[1]; step.Path != "cmd/api/main.go" || step.Line != 11 || !strings.Contains(step.Snippet, "order.NewMemoryRepository") {
		t.Fatalf("anchored repository step = %+v", step)
	}
	if step := result.Flows[0].Steps[2]; step.Path != "cmd/api/main.go" || step.Line != 12 || !strings.Contains(step.Snippet, "order.NewService") {
		t.Fatalf("anchored service wiring step = %+v", step)
	}
	if flow := result.Flows[1]; flow.Summary == "" || !strings.Contains(flow.Motivation, "reject malformed") || !strings.Contains(flow.Details, "[2b]") {
		t.Fatalf("per-flow guide was not materialized: %+v", flow)
	}
	// The verified anchorText re-anchors 2b inside Submit itself instead of the
	// call site, at the exact snippet line the model copied.
	if step := result.Flows[1].Steps[1]; step.Path != "internal/order/service.go" || step.Line != 22 || step.Snippet != "order.CreatedAt = s.clock().UTC()" {
		t.Fatalf("anchorText-anchored Submit step = %+v", step)
	}
	if step := result.Flows[1].Steps[1]; len(step.Notes) != 2 || step.Notes[0] != "validate before persisting" || step.Notes[1] != "stamp UTC creation time" {
		t.Fatalf("step notes = %+v", step.Notes)
	}
	if step := result.Flows[1].Steps[2]; step.Path != "internal/order/service.go" || !strings.Contains(step.Snippet, "s.repository.Save") {
		t.Fatalf("anchored Save step = %+v", step)
	}
	// Depth is derived from factual call edges: entry at 0, callees nested.
	for i, want := range []int{0, 1, 1, 1} {
		if got := result.Flows[0].Steps[i].Depth; got != want {
			t.Fatalf("flow 0 step %d depth = %d, want %d", i, got, want)
		}
	}
	for i, want := range []int{0, 1, 2} {
		if got := result.Flows[1].Steps[i].Depth; got != want {
			t.Fatalf("flow 1 step %d depth = %d, want %d", i, got, want)
		}
	}
	for _, node := range result.Nodes {
		for _, forbidden := range []string{"make", "s.clock", "err.Error", "UTC"} {
			if node.Label == forbidden {
				t.Fatalf("false external node %q survived: %+v", forbidden, node)
			}
		}
	}
	stdlibCounts := make(map[string]int)
	for _, node := range result.Nodes {
		if node.Kind == "stdlib" {
			stdlibCounts[node.Label]++
		}
	}
	for packageName, count := range stdlibCounts {
		if count != 1 {
			t.Fatalf("stdlib package %q has %d nodes, want one compact node", packageName, count)
		}
	}
}

func TestBuildTracePrioritizesCallsBeforeImports(t *testing.T) {
	t.Parallel()
	trace := buildTrace(
		[]domain.CodemapNode{
			{ID: "file", Label: "main.go"},
			{ID: "main", Label: "main"},
			{ID: "http", Label: "net/http"},
			{ID: "repo", Label: "NewMemoryRepository"},
		},
		[]domain.CodemapEdge{
			{Source: "file", Target: "http", Type: "imports"},
			{Source: "main", Target: "repo", Type: "calls"},
		},
	)
	if len(trace) == 0 {
		t.Fatal("trace is empty")
	}
	if trace[0] != "main —calls→ NewMemoryRepository" {
		t.Fatalf("first trace step = %q, want call flow first", trace[0])
	}
}

func TestCodemapEdgeIDDistinguishesSQLiteZeroIDsBySource(t *testing.T) {
	t.Parallel()
	first := domain.Edge{ID: 0, FromSymbolID: "main", ToName: "Save", Type: "calls", Path: "main.go", Line: 10}
	second := domain.Edge{ID: 0, FromSymbolID: "Submit", ToName: "Save", Type: "calls", Path: "service.go", Line: 22}
	firstID := codemapEdgeID(first, "save")
	if secondID := codemapEdgeID(second, "save"); firstID == secondID {
		t.Fatalf("zero-ID edges collided: %q", firstID)
	}
	if repeat := codemapEdgeID(first, "save"); repeat != firstID {
		t.Fatalf("edge ID is not deterministic: first=%q repeat=%q", firstID, repeat)
	}
}

func indexSource(t *testing.T, repository repository.Store, engine *codeparser.Engine, path, source string) {
	t.Helper()
	symbols, edges, language, err := engine.Parse(path, []byte(source))
	if err != nil {
		t.Fatalf("Parse(%s) error = %v", path, err)
	}
	repository.ReplaceFile(domain.ParsedFile{
		File:    domain.File{Path: path, Language: language, Hash: path, Size: int64(len(source)), IndexedAt: time.Now()},
		Symbols: symbols,
		Edges:   edges,
	})
}

func TestClassifyCodemapExternalDoesNotApplyGoStdlibHeuristicToOtherLanguages(t *testing.T) {
	t.Parallel()
	node, keep := classifyCodemapExternal(
		domain.Edge{Type: "imports", ToName: "react"},
		domain.Symbol{Language: "typescript"},
		nil,
	)
	if !keep || node.Kind != "external" || node.Group != "External" {
		t.Fatalf("TypeScript import classified as %+v/%v, want generic external node", node, keep)
	}
}

type capturingProvider struct {
	mu            sync.Mutex
	response      string
	structured    string
	err           error
	systemPrompt  string
	userPrompt    string
	systemPrompts []string
	userPrompts   []string
	maxTokens     int
}

func (p *capturingProvider) Name() string { return "capture" }

func (p *capturingProvider) Available() bool { return true }

func (p *capturingProvider) Complete(_ context.Context, systemPrompt, userPrompt string, maxTokens int) (string, error) {
	p.mu.Lock()
	p.systemPrompt = systemPrompt
	p.userPrompt = userPrompt
	p.systemPrompts = append(p.systemPrompts, systemPrompt)
	p.userPrompts = append(p.userPrompts, userPrompt)
	if maxTokens > p.maxTokens {
		p.maxTokens = maxTokens
	}
	err := p.err
	structured := p.structured
	response := p.response
	p.mu.Unlock()
	if err != nil {
		return "", err
	}
	if structured != "" {
		return structured, nil
	}
	return structuredStub(systemPrompt, response), nil
}

// structuredStub returns the minimal valid structured output for whichever schema
// the system prompt requests (no cited evidence IDs → trivially grounded), with
// the configured response carried as the human-visible text. A non-structured
// prompt returns response unchanged.
func structuredStub(systemPrompt, response string) string {
	switch {
	case strings.Contains(systemPrompt, "explanation/v2"):
		summary := response
		if summary == "" {
			summary = "summary"
		}
		return `{"schemaVersion":"explanation/v2","summary":` + strconv.Quote(summary) + `,"observations":[],"inferences":[],"uncertainties":[],"changeImpact":[]}`
	case strings.Contains(systemPrompt, "codemap-narrative/v2"):
		overview := response
		if overview == "" {
			overview = "The generated map explains the grounded execution flow and its observed source boundaries."
		}
		overview += " It names the participating components, the observed boundaries, and the scope supported by indexed evidence."
		motivation := strings.Repeat("The application keeps transport, business rules, and persistence responsibilities separate so callers can follow each boundary in the observed code. ", 2)
		details := strings.Repeat("The grounded path starts at the selected entrypoint, follows validated local calls, records state changes supported by snippets, and ends at the observed repository boundary. Each step remains tied to backend-owned source bytes. ", 2)
		return `{"schemaVersion":"codemap-narrative/v2","title":"Map","overview":` + strconv.Quote(overview) + `,"motivation":` + strconv.Quote(motivation) + `,"details":` + strconv.Quote(details) + `,"trace":[],"flows":[],"claims":[],"inferences":[],"uncertainties":[]}`
	case strings.Contains(systemPrompt, "wiki-page/v4"):
		text := response
		if text == "" {
			text = "Content"
		}
		return `{"schemaVersion":"wiki-page/v4","title":` + strconv.Quote(text) + `,"sections":[{"heading":` + strconv.Quote(text) + `,"claims":[]}],"relatedPages":[],"inferences":[],"limitations":[]}`
	default:
		return response
	}
}

func (p *capturingProvider) Embed(context.Context, []string) ([][]float64, error) {
	return nil, ai.ErrUnavailable
}

func assertContains(t *testing.T, value, substring string) {
	t.Helper()
	if !strings.Contains(value, substring) {
		t.Fatalf("expected value to contain %q\nvalue:\n%s", substring, value)
	}
}
