package service

import (
	"context"
	"errors"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/ThalesMMS/CodeAtlas/internal/ai"
	"github.com/ThalesMMS/CodeAtlas/internal/aiout"
	"github.com/ThalesMMS/CodeAtlas/internal/apperror"
	"github.com/ThalesMMS/CodeAtlas/internal/domain"
	"github.com/ThalesMMS/CodeAtlas/internal/repository"
)

func seededWikiStore(t *testing.T) repository.Store {
	t.Helper()
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	repository.ReplaceFile(domain.ParsedFile{
		File: domain.File{Path: "main.go", Language: "go", Hash: "main", IndexedAt: time.Now()},
		Symbols: []domain.Symbol{
			{ID: "file", Path: "main.go", Name: "main.go", QualifiedName: "main.go", Kind: "file",
				Range: domain.Range{Start: domain.Position{Line: 1, Column: 1}, End: domain.Position{Line: 3, Column: 1}}, Summary: "Main file."},
			{ID: "main", Path: "main.go", Name: "main", QualifiedName: "main.go::main", Kind: "function",
				Range: domain.Range{Start: domain.Position{Line: 3, Column: 1}, End: domain.Position{Line: 3, Column: 14}}, Summary: "Entry point."},
		},
	})
	return repository
}

func addFile(repository repository.Store, path string) {
	repository.ReplaceFile(domain.ParsedFile{
		File: domain.File{Path: path, Language: "go", Hash: path, IndexedAt: time.Now()},
		Symbols: []domain.Symbol{
			{ID: path + ":file", Path: path, Name: path, QualifiedName: path, Kind: "file",
				Range: domain.Range{Start: domain.Position{Line: 1, Column: 1}, End: domain.Position{Line: 2, Column: 1}}, Summary: "extra"},
		},
	})
}

// blockingProvider blocks inside Complete until released, signalling first entry.
type blockingProvider struct {
	response string
	release  chan struct{}
	entered  chan struct{}
	once     sync.Once
}

func (p *blockingProvider) Name() string    { return "capture" }
func (p *blockingProvider) Available() bool { return true }
func (p *blockingProvider) Complete(_ context.Context, systemPrompt, _ string, _ int) (string, error) {
	p.once.Do(func() { close(p.entered) })
	<-p.release
	return structuredStub(systemPrompt, p.response), nil
}
func (p *blockingProvider) Embed(context.Context, []string) ([][]float64, error) {
	return nil, errors.New("disabled")
}

// mutatingProvider changes the index during the first Complete call, simulating a
// concurrent index update that makes the in-flight generation obsolete.
type mutatingProvider struct {
	store    repository.Store
	response string
	once     sync.Once
}

func (p *mutatingProvider) Name() string    { return "capture" }
func (p *mutatingProvider) Available() bool { return true }
func (p *mutatingProvider) Complete(_ context.Context, systemPrompt, _ string, _ int) (string, error) {
	p.once.Do(func() { addFile(p.store, "mutated.go") })
	return structuredStub(systemPrompt, p.response), nil
}
func (p *mutatingProvider) Embed(context.Context, []string) ([][]float64, error) {
	return nil, errors.New("disabled")
}

func TestDeepWikiGeneratesPagesWithProviderMetadata(t *testing.T) {
	t.Parallel()
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	repository.ReplaceFile(domain.ParsedFile{
		File: domain.File{Path: "main.go", Language: "go", Hash: "main", IndexedAt: time.Now()},
		Symbols: []domain.Symbol{
			{
				ID: "file", Path: "main.go", Name: "main.go", QualifiedName: "main.go", Kind: "file",
				Range:   domain.Range{Start: domain.Position{Line: 1, Column: 1}, End: domain.Position{Line: 3, Column: 1}},
				Summary: "Main file.",
			},
			{
				ID: "main", Path: "main.go", Name: "main", QualifiedName: "main.go::main", Kind: "function",
				Range:   domain.Range{Start: domain.Position{Line: 3, Column: 1}, End: domain.Position{Line: 3, Column: 14}},
				Summary: "Entry point.",
			},
		},
	})

	provider := &capturingProvider{response: "# Page generated by the LLM"}
	service := NewDeepWikiService(repository, provider)
	pages, err := service.Generate(context.Background())
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(pages) == 0 {
		t.Fatal("Generate() returned no pages")
	}
	for _, page := range pages {
		if page.Provider != provider.Name() {
			t.Fatalf("page %q provider = %q, want %q", page.Slug, page.Provider, provider.Name())
		}
		// The page is now rendered server-side from the structured WikiPageContent,
		// so the LLM text appears inside the rendered Markdown.
		if page.Archetype != "glossary" && !strings.Contains(page.Markdown, provider.response) {
			t.Fatalf("page %q markdown = %q, want rendered LLM content", page.Slug, page.Markdown)
		}
		if page.OutputSchemaVersion != "wiki-page/v4" {
			t.Fatalf("page %q output schema = %q, want wiki-page/v4", page.Slug, page.OutputSchemaVersion)
		}
		if page.Archetype != "glossary" {
			if page.Diagram == nil || page.Diagram.Version != "mermaid/v1" || page.Diagram.Source == "" {
				t.Fatalf("page %q deterministic diagram = %+v", page.Slug, page.Diagram)
			}
			if !strings.Contains(page.Markdown, "```mermaid\n") || !strings.Contains(page.Markdown, "**Diagram sources:**") {
				t.Fatalf("page %q Markdown lacks rendered diagram/sources: %q", page.Slug, page.Markdown)
			}
		}
	}
	for index := range provider.userPrompts {
		if strings.Contains(provider.userPrompts[index], "graph TD") || strings.Contains(provider.systemPrompts[index], "mermaid") {
			t.Fatalf("deterministic diagram leaked into model request %d", index)
		}
	}
}

func TestDeepWikiUsesEnoughOutputBudgetForStructuredPages(t *testing.T) {
	repository := seededWikiStore(t)
	provider := &capturingProvider{response: "# Page generated by the LLM"}
	service := NewDeepWikiService(repository, provider)

	if _, err := service.Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if provider.maxTokens < 8000 {
		t.Fatalf("deepwiki max output tokens = %d, want at least 8000 to avoid structured page truncation", provider.maxTokens)
	}
}

func TestDeepWikiReturnsProviderErrorInsteadOfDraftPage(t *testing.T) {
	t.Parallel()
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	repository.ReplaceFile(domain.ParsedFile{
		File: domain.File{Path: "main.go", Language: "go", Hash: "main", IndexedAt: time.Now()},
		Symbols: []domain.Symbol{
			{
				ID: "file", Path: "main.go", Name: "main.go", QualifiedName: "main.go", Kind: "file",
				Range:   domain.Range{Start: domain.Position{Line: 1, Column: 1}, End: domain.Position{Line: 3, Column: 1}},
				Summary: "Main file.",
			},
		},
	})

	service := NewDeepWikiService(repository, &capturingProvider{err: errors.New("LLM returned an empty response")})
	_, err = service.Generate(context.Background())
	if err == nil {
		t.Fatal("Generate() succeeded with a failing provider; want error")
	}
	appErr, ok := apperror.As(err)
	if !ok || appErr.Code != apperror.CodeProviderUnavailable {
		t.Fatalf("error = %v, want PROVIDER_UNAVAILABLE app error", err)
	}
	if appErr.Cause == nil || !strings.Contains(appErr.Cause.Error(), "LLM returned an empty response") {
		t.Fatalf("provider cause not preserved: %v", appErr.Cause)
	}
	if pages := service.Pages(); len(pages) != 0 {
		t.Fatalf("Pages() = %#v, want no draft pages persisted", pages)
	}
}

func TestDeepWikiCanRecoverOnFifthPageResponse(t *testing.T) {
	t.Parallel()
	store := seededWikiStore(t)
	provider := &recoveringWikiProvider{}
	if _, err := NewDeepWikiService(store, provider).Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v, want recovery on fifth page response", err)
	}
	if provider.pageCalls < 5 {
		t.Fatalf("page calls = %d, want at least 5", provider.pageCalls)
	}
}

func TestDeepWikiCollectionStateTransitions(t *testing.T) {
	t.Parallel()
	repository := seededWikiStore(t)
	service := NewDeepWikiService(repository, &capturingProvider{response: "# page"})

	if got := service.Collection().Status; got != domain.DeepWikiNotGenerated {
		t.Fatalf("initial status = %q, want not_generated", got)
	}

	if _, err := service.Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	collection := service.Collection()
	if collection.Status != domain.DeepWikiReady || len(collection.Pages) == 0 || collection.SnapshotID == "" {
		t.Fatalf("after generate = %#v, want ready with pages and snapshot", collection)
	}

	// Mutating the index makes the published pages stale.
	addFile(repository, "extra.go")
	if got := service.Collection().Status; got != domain.DeepWikiStale {
		t.Fatalf("after index change status = %q, want stale", got)
	}
}

func TestDeepWikiConcurrentRefreshRejected(t *testing.T) {
	t.Parallel()
	repository := seededWikiStore(t)
	provider := &blockingProvider{response: "# page", release: make(chan struct{}), entered: make(chan struct{})}
	service := NewDeepWikiService(repository, provider)

	done := make(chan error, 1)
	go func() {
		_, err := service.Generate(context.Background())
		done <- err
	}()
	<-provider.entered // the first generation is now in progress

	if got := service.Collection().Status; got != domain.DeepWikiGenerating {
		t.Fatalf("status during generation = %q, want generating", got)
	}
	if _, err := service.Generate(context.Background()); !errors.Is(err, ErrGenerationInProgress) {
		t.Fatalf("concurrent Generate() error = %v, want ErrGenerationInProgress", err)
	}

	close(provider.release)
	if err := <-done; err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}
}

func TestDeepWikiObsoleteSnapshotNotPublished(t *testing.T) {
	t.Parallel()
	repository := seededWikiStore(t)
	if _, err := NewDeepWikiService(repository, &capturingProvider{response: "# base"}).Generate(context.Background()); err != nil {
		t.Fatalf("baseline Generate() error = %v", err)
	}

	service := NewDeepWikiService(repository, &mutatingProvider{store: repository, response: "# obsolete"})
	if _, err := service.Generate(context.Background()); !errors.Is(err, ErrSnapshotChanged) {
		t.Fatalf("Generate() error = %v, want ErrSnapshotChanged", err)
	}
	// The previous valid pages must remain.
	for _, page := range service.Pages() {
		if page.Markdown == "# obsolete" {
			t.Fatal("obsolete result was published as current")
		}
	}
	if len(service.Pages()) == 0 {
		t.Fatal("previous pages were lost")
	}
}

func TestDeepWikiFailedRefreshPreservesPages(t *testing.T) {
	t.Parallel()
	repository := seededWikiStore(t)
	if _, err := NewDeepWikiService(repository, &capturingProvider{response: "# base"}).Generate(context.Background()); err != nil {
		t.Fatalf("baseline Generate() error = %v", err)
	}

	service := NewDeepWikiService(repository, &capturingProvider{err: errors.New("LLM offline")})
	if _, err := service.Generate(context.Background()); err == nil {
		t.Fatal("Generate() succeeded with a failing provider; want error")
	}
	collection := service.Collection()
	if collection.Status != domain.DeepWikiFailed {
		t.Fatalf("status = %q, want failed", collection.Status)
	}
	if len(collection.Pages) == 0 {
		t.Fatal("failed refresh wiped previously valid pages")
	}
	if collection.LastError == "" {
		t.Fatal("failed refresh did not record an error")
	}
}

func TestDeepWikiPagesIgnoresProviderlessCachedPages(t *testing.T) {
	t.Parallel()
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	repository.ReplaceWikiPages([]domain.WikiPage{
		{Slug: "overview", Title: "Overview", Markdown: "# Old draft"},
		{Slug: "current", Title: "Current", Markdown: "# Current", Provider: "capture"},
	})

	service := NewDeepWikiService(repository, &capturingProvider{response: "# Current"})
	pages := service.Pages()
	if len(pages) != 1 || pages[0].Slug != "current" {
		t.Fatalf("Pages() = %#v, want only current-provider cached page", pages)
	}
}

func TestOrderWikiPagesPlacesParentsBeforeChildren(t *testing.T) {
	t.Parallel()
	pages := []domain.WikiPage{
		{Slug: "4.1-service", ParentSlug: "4-backend"},
		{Slug: "2-architecture", ParentSlug: "overview"},
		{Slug: "overview"},
		{Slug: "4-backend", ParentSlug: "overview"},
		{Slug: "1-getting-started", ParentSlug: "overview"},
	}
	ordered := orderWikiPages(pages)
	var slugs []string
	for _, page := range ordered {
		slugs = append(slugs, page.Slug)
	}
	want := []string{"overview", "1-getting-started", "2-architecture", "4-backend", "4.1-service"}
	if strings.Join(slugs, ",") != strings.Join(want, ",") {
		t.Fatalf("ordered slugs = %#v, want %#v", slugs, want)
	}
}

type recoveringWikiProvider struct {
	mu        sync.Mutex
	pageCalls int
}

func (*recoveringWikiProvider) Name() string    { return "recovering-wiki" }
func (*recoveringWikiProvider) Available() bool { return true }

func (p *recoveringWikiProvider) Complete(_ context.Context, systemPrompt, _ string, _ int) (string, error) {
	if strings.Contains(systemPrompt, aiout.WikiPageSchemaVersion) {
		p.mu.Lock()
		p.pageCalls++
		call := p.pageCalls
		p.mu.Unlock()
		if call < 5 {
			return `{}`, nil
		}
	}
	return structuredStub(systemPrompt, "Grounded page"), nil
}

func (*recoveringWikiProvider) Embed(context.Context, []string) ([][]float64, error) {
	return nil, ai.ErrUnavailable
}
