package service

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/ThalesMMS/CodeAtlas/internal/ai"
	"github.com/ThalesMMS/CodeAtlas/internal/aiout"
	"github.com/ThalesMMS/CodeAtlas/internal/apperror"
	"github.com/ThalesMMS/CodeAtlas/internal/contextpack"
	"github.com/ThalesMMS/CodeAtlas/internal/domain"
	"github.com/ThalesMMS/CodeAtlas/internal/indexer"
	codeparser "github.com/ThalesMMS/CodeAtlas/internal/parser"
	"github.com/ThalesMMS/CodeAtlas/internal/repository"
	"github.com/ThalesMMS/CodeAtlas/internal/semantic"
	"github.com/ThalesMMS/CodeAtlas/internal/semevidence"
)

func TestExplainResolvesPackageQualifier(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	writeFile(t, root, "cmd/api/main.go", `package main

import (
	"log"
	"net/http"

	"example.com/tinycommerce/internal/order"
)

func main() {
	repository := order.NewMemoryRepository()
	service := order.NewService(repository)
	handler := order.NewHandler(service)

	mux := http.NewServeMux()
	mux.HandleFunc("POST /orders", handler.Create)
	log.Fatal(http.ListenAndServe("127.0.0.1:8090", mux))
}
`)
	writeFile(t, root, "internal/order/http.go", `package order

import (
	"encoding/json"
	"net/http"
)

type Handler struct {
	service *Service
}

func NewHandler(service *Service) *Handler {
	return &Handler{service: service}
}

func (h *Handler) Create(response http.ResponseWriter, request *http.Request) {
	var input Order
	if err := json.NewDecoder(request.Body).Decode(&input); err != nil {
		http.Error(response, "invalid payload", http.StatusBadRequest)
		return
	}
	if err := h.service.Submit(request.Context(), input); err != nil {
		http.Error(response, err.Error(), http.StatusUnprocessableEntity)
		return
	}
	response.WriteHeader(http.StatusCreated)
}
`)
	writeFile(t, root, "internal/order/service.go", `package order

import (
	"context"
	"errors"
	"time"
)

type Service struct {
	repository Repository
	clock      func() time.Time
}

func NewService(repository Repository) *Service {
	return &Service{repository: repository, clock: time.Now}
}

func (s *Service) Submit(ctx context.Context, order Order) error {
	if err := validateOrder(order); err != nil {
		return err
	}
	order.CreatedAt = s.clock().UTC()
	return s.repository.Save(ctx, order)
}

func validateOrder(order Order) error {
	if order.ID == "" || order.CustomerID == "" {
		return errors.New("order and customer identifiers are required")
	}
	if order.TotalCents <= 0 {
		return errors.New("order total must be positive")
	}
	return nil
}
`)
	writeFile(t, root, "internal/order/repository.go", `package order

import (
	"context"
	"sync"
)

type Repository interface {
	Save(ctx context.Context, order Order) error
	Find(ctx context.Context, id string) (Order, bool)
}

type MemoryRepository struct {
	mu     sync.RWMutex
	orders map[string]Order
}

func NewMemoryRepository() *MemoryRepository {
	return &MemoryRepository{orders: make(map[string]Order)}
}

func (r *MemoryRepository) Save(_ context.Context, order Order) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.orders[order.ID] = order
	return nil
}

func (r *MemoryRepository) Find(_ context.Context, id string) (Order, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	value, found := r.orders[id]
	return value, found
}
`)
	writeFile(t, root, "internal/order/model.go", `package order

import "time"

type Order struct {
	ID         string
	CustomerID string
	TotalCents int64
	CreatedAt  time.Time
}
`)
	writeFile(t, root, "internal/order/service_test.go", `package order

import "testing"

func TestSubmit(t *testing.T) {
	service := NewService(NewMemoryRepository())
	_ = service
}
`)
	writeFile(t, root, "go.mod", `module example.com/tinycommerce

go 1.22
`)

	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	parser := codeparser.New()
	backgroundIndexer := indexer.New(root, 1_500_000, parser, repository)
	if err := backgroundIndexer.Scan(context.Background()); err != nil {
		t.Fatalf("Scan() error = %v", err)
	}

	workspace := NewWorkspace(root)
	provider := &capturingProvider{response: "## Explanation generated by the LLM"}
	explainer := NewExplainer(repository, workspace, provider)

	cases := []struct {
		name     string
		column   int
		want     string
		wantKind string
	}{
		{"package qualifier order", 13, "order", domain.KindPackage},
		{"dot between order and NewHandler", 18, "order", domain.KindPackage},
		{"function name NewHandler", 19, "NewHandler", domain.KindFunction},
	}
	var packageSymbolID string
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			explanation, err := explainer.Explain(context.Background(), domain.ExplainRequest{
				Path:   "cmd/api/main.go",
				Line:   13,
				Column: tc.column,
				Depth:  "hover",
			})
			if err != nil {
				t.Fatalf("Explain() error = %v", err)
			}
			if explanation.Symbol.Name != tc.want {
				t.Fatalf("column %d: got name=%q, want %q", tc.column, explanation.Symbol.Name, tc.want)
			}
			if explanation.Symbol.Kind != tc.wantKind {
				t.Fatalf("column %d: got kind=%q, want %q", tc.column, explanation.Symbol.Kind, tc.wantKind)
			}
			if explanation.Provider != provider.Name() {
				t.Fatalf("provider = %q, want %q", explanation.Provider, provider.Name())
			}
			if explanation.Markdown != provider.response {
				t.Fatalf("markdown = %q, want LLM response", explanation.Markdown)
			}
			// Hover now flows through the HoverPolicy ContextPack: the response must
			// carry the pack hash and policy version, and at least the target evidence.
			if explanation.ContextPackHash == "" || explanation.PolicyVersion != "hover.v3" {
				t.Fatalf("missing ContextPack provenance: hash=%q policy=%q", explanation.ContextPackHash, explanation.PolicyVersion)
			}
			if explanation.Feature != domain.ExplainFeatureHover || explanation.PromptVersion != "hover-v3" {
				t.Fatalf("feature/prompt metadata = %q/%q", explanation.Feature, explanation.PromptVersion)
			}
			if explanation.Result.SchemaVersion != "explanation/v2" || explanation.Result.Summary != provider.response {
				t.Fatalf("structured result = %#v", explanation.Result)
			}
			if len(explanation.Evidence) == 0 {
				t.Fatal("hover pack produced no evidence")
			}
			targetEvidenceFound := false
			for _, item := range explanation.Evidence {
				if item.ID == "" {
					t.Fatalf("evidence ID missing: %#v", item)
				}
				if item.SymbolID == explanation.Symbol.ID && item.OccurrenceID != "" {
					targetEvidenceFound = true
				}
			}
			if !targetEvidenceFound {
				t.Fatalf("target evidence missing for %s: %+v", explanation.Symbol.ID, explanation.Evidence)
			}
			if tc.wantKind == domain.KindPackage {
				packageSymbolID = explanation.Symbol.ID
				if explanation.Symbol.QualifiedName != "example.com/tinycommerce/internal/order" {
					t.Fatalf("package qualified name = %q", explanation.Symbol.QualifiedName)
				}
				assertHoverPackageEvidence(t, explanation.Evidence)
			}
			if tc.name == "function name NewHandler" {
				byOccurrence, err := explainer.Explain(context.Background(), domain.ExplainRequest{
					Feature: domain.ExplainFeatureHover,
					Target:  &domain.ExplainTarget{OccurrenceID: explanation.OccurrenceID},
				})
				if err != nil {
					t.Fatalf("Explain(target.occurrenceId) error = %v", err)
				}
				if byOccurrence.Symbol.Name != explanation.Symbol.Name {
					t.Fatalf("occurrence target resolved %q, want %q", byOccurrence.Symbol.Name, explanation.Symbol.Name)
				}
			}
		})
	}

	pack, err := contextpack.NewPacker(repository, map[contextpack.Feature]contextpack.Policy{
		contextpack.FeatureSeeMore: contextpack.NewSeeMorePolicy(),
	}).Build(context.Background(), contextpack.ContextRequest{
		Feature: contextpack.FeatureSeeMore, SnapshotID: repository.SnapshotID(),
		Location: &contextpack.SourceLocation{Path: "cmd/api/main.go", Line: 13, Column: 13, SymbolID: domain.SymbolID(packageSymbolID)},
	})
	if err != nil {
		t.Fatalf("build package See More pack: %v", err)
	}
	assertSeeMorePackagePack(t, pack)
	view := repository.Snapshot()
	defer view.Close()
	seeAlso := packSeeAlso(pack, view, packageSymbolID, 5)
	labels := make(map[string]bool, len(seeAlso))
	for _, ref := range seeAlso {
		labels[ref.Label] = true
	}
	for _, name := range []string{"Order", "Repository", "MemoryRepository"} {
		if !labels[name] {
			t.Errorf("deterministic See Also lacks %s: %+v", name, seeAlso)
		}
	}
}

func assertSeeMorePackagePack(t *testing.T, pack contextpack.ContextPack) {
	t.Helper()
	requiredPaths := map[string]bool{
		"internal/order/http.go": false, "internal/order/model.go": false,
		"internal/order/repository.go": false, "internal/order/service.go": false,
		"internal/order/service_test.go": false,
	}
	wants := map[string]bool{"Order": false, "Repository": false, "MemoryRepository": false}
	testFound, usageFound := false, false
	for _, evidence := range pack.Evidence {
		if _, tracked := requiredPaths[evidence.Path]; tracked {
			requiredPaths[evidence.Path] = true
		}
		for name := range wants {
			if strings.Contains(evidence.Title, name) {
				wants[name] = true
			}
		}
		if evidence.Kind == contextpack.KindTest && evidence.Path == "internal/order/service_test.go" {
			testFound = true
		}
		if evidence.Relation == "usage_site" && strings.Contains(evidence.Content, "order.NewHandler") {
			usageFound = true
		}
	}
	for path, found := range requiredPaths {
		if !found {
			t.Errorf("See More package pack lacks evidence from %s", path)
		}
	}
	for name, found := range wants {
		if !found {
			t.Errorf("See More package pack lacks %s", name)
		}
	}
	if !testFound || !usageFound {
		t.Fatalf("See More package pack lacks test/usage evidence: test=%v usage=%v", testFound, usageFound)
	}
}

func assertHoverPackageEvidence(t *testing.T, evidence []domain.Evidence) {
	t.Helper()
	usageFound := false
	constructors := map[string]bool{"NewHandler": false, "NewMemoryRepository": false, "NewService": false}
	for _, item := range evidence {
		if item.Relation == "usage_site" && strings.Contains(item.Content, "order.NewHandler") &&
			strings.Contains(item.Content, "order.NewMemoryRepository") && strings.Contains(item.Content, "order.NewService") {
			usageFound = true
		}
		if item.Relation == "package_api" {
			for name := range constructors {
				if strings.Contains(item.Title, name) {
					constructors[name] = true
				}
			}
		}
	}
	if !usageFound {
		t.Fatalf("hover package evidence lacks the exact usage site: %+v", evidence)
	}
	for name, found := range constructors {
		if !found {
			t.Fatalf("hover package evidence lacks constructor %s: %+v", name, evidence)
		}
	}
}

func TestHoverUsesExactLSPDefinitionAndPrioritizesHoverText(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "main.go", `package main

// Target returns the configured result.
func Target() {}
func main() { Target() }
`)
	repo, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	backgroundIndexer := indexer.New(root, 1_500_000, codeparser.New(), repo)
	if err := backgroundIndexer.Scan(context.Background()); err != nil {
		t.Fatalf("Scan() error = %v", err)
	}

	semanticProvider := &hoverSemanticProvider{
		definition: semantic.SemanticFact{
			Kind: semantic.KindDefinition,
			Location: semantic.SourceLocation{Path: "main.go", Range: domain.Range{
				Start: domain.Position{Line: 4, Column: 6}, End: domain.Position{Line: 4, Column: 12},
			}},
		},
		hover: semantic.SemanticFact{
			Kind: semantic.KindHoverType, Subject: semantic.SymbolRef{Name: "Target"},
			Location:   semantic.SourceLocation{Path: "main.go", Range: domain.Range{Start: domain.Position{Line: 5, Column: 15}}},
			Detail:     "Target returns the configured result.\nfunc Target()",
			Confidence: semantic.ConfidenceLanguageServerResolved,
			Provenance: semantic.Provenance{Source: semantic.SourceGopls, ProviderID: "gopls"},
		},
	}
	explainer := NewExplainer(repo, NewWorkspace(root), &capturingProvider{response: "Target returns the configured result."})
	explainer.SetSemanticSources(semanticProvider, semevidence.NewCollector(semanticProvider, time.Second, 8))

	explanation, err := explainer.Explain(context.Background(), domain.ExplainRequest{
		Path: "main.go", Line: 5, Column: 15, Feature: domain.ExplainFeatureHover,
	})
	if err != nil {
		t.Fatalf("Explain() error = %v", err)
	}
	if explanation.Symbol.Name != "Target" || explanation.Symbol.Kind != domain.KindFunction {
		t.Fatalf("resolved symbol = %+v, want local function Target", explanation.Symbol)
	}
	query := semanticProvider.definitionQuery()
	if query.Path != "main.go" || query.Position != (domain.Position{Line: 5, Column: 15, Encoding: "utf-8"}) {
		t.Fatalf("definition query = %+v, want exact hover position", query)
	}
	if len(explanation.Evidence) == 0 || explanation.Evidence[0].Kind != contextpack.KindLSPFact ||
		!strings.Contains(explanation.Evidence[0].Content, "Target returns the configured result") {
		t.Fatalf("primary evidence is not gopls hover text: %+v", explanation.Evidence)
	}
	if len(explanation.Evidence[0].Provenance) == 0 || explanation.Evidence[0].Provenance[0].Source != semantic.SourceGopls {
		t.Fatalf("gopls provenance missing: %+v", explanation.Evidence[0].Provenance)
	}
}

type hoverSemanticProvider struct {
	mu         sync.Mutex
	lastDef    semantic.SemanticQuery
	definition semantic.SemanticFact
	hover      semantic.SemanticFact
}

func (p *hoverSemanticProvider) ID() semantic.SemanticProviderID { return "gopls" }
func (p *hoverSemanticProvider) Capabilities(context.Context) (semantic.SemanticCapabilities, error) {
	return semantic.SemanticCapabilities{Hover: true, Definition: true, Diagnostics: true}, nil
}
func (p *hoverSemanticProvider) Hover(context.Context, semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	return []semantic.SemanticFact{p.hover}, nil
}
func (p *hoverSemanticProvider) Definitions(_ context.Context, query semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	p.mu.Lock()
	p.lastDef = query
	p.mu.Unlock()
	return []semantic.SemanticFact{p.definition}, nil
}
func (p *hoverSemanticProvider) References(context.Context, semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	return nil, semantic.CapabilityUnsupported("references")
}
func (p *hoverSemanticProvider) Implementations(context.Context, semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	return nil, semantic.CapabilityUnsupported("implementation")
}
func (p *hoverSemanticProvider) IncomingCalls(context.Context, semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	return nil, semantic.CapabilityUnsupported("incomingCalls")
}
func (p *hoverSemanticProvider) OutgoingCalls(context.Context, semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	return nil, semantic.CapabilityUnsupported("outgoingCalls")
}
func (p *hoverSemanticProvider) Diagnostics(context.Context, semantic.SemanticQuery) ([]semantic.SemanticFact, error) {
	return nil, nil
}
func (p *hoverSemanticProvider) definitionQuery() semantic.SemanticQuery {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.lastDef
}

type explainRequestCapturingProvider struct {
	requests []ai.GenerationRequest
}

func (p *explainRequestCapturingProvider) Name() string    { return "request-capture" }
func (p *explainRequestCapturingProvider) Available() bool { return true }
func (p *explainRequestCapturingProvider) Complete(context.Context, string, string, int) (string, error) {
	return "", errors.New("unexpected unstructured completion")
}
func (p *explainRequestCapturingProvider) CompleteStructured(_ context.Context, request ai.GenerationRequest) (ai.GenerationResult, error) {
	p.requests = append(p.requests, request)
	return ai.GenerationResult{
		RawJSON:  []byte(`{"schemaVersion":"explanation/v2","summary":"Structured summary","observations":[],"inferences":[],"uncertainties":[],"changeImpact":[]}`),
		Provider: p.Name(),
	}, nil
}
func TestExplainReasoningEffortOnlyDisablesHover(t *testing.T) {
	for _, test := range []struct {
		feature contextpack.Feature
		want    string
	}{
		{feature: contextpack.FeatureHover, want: "none"},
		{feature: contextpack.FeatureSeeMore, want: ""},
	} {
		if got := explainReasoningEffort(test.feature); got != test.want {
			t.Errorf("explainReasoningEffort(%q) = %q, want %q", test.feature, got, test.want)
		}
	}
}

func TestHoverDisablesReasoningAndKeepsStructuredOutputBudget(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "web/src/checkout.ts", `import { OrderInput, submitOrder } from "./api"

export class CheckoutController {
  async completeCheckout(input: OrderInput): Promise<string> {
    validateCheckout(input)
    await submitOrder(input)
    return input.id
  }
}

function validateCheckout(input: OrderInput): void {
  if (!input.id || !input.customerId || input.totalCents <= 0) {
    throw new Error("invalid checkout")
  }
}
`)
	writeFile(t, root, "web/src/api.ts", `export interface OrderInput {
  id: string
  customerId: string
  totalCents: number
}

export async function submitOrder(input: OrderInput): Promise<void> {
  await fetch("/orders", { method: "POST", body: JSON.stringify(input) })
}
`)
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	parser := codeparser.New()
	backgroundIndexer := indexer.New(root, 1_500_000, parser, repository)
	if err := backgroundIndexer.Scan(context.Background()); err != nil {
		t.Fatalf("Scan() error = %v", err)
	}

	provider := &explainRequestCapturingProvider{}
	explainer := NewExplainer(repository, NewWorkspace(root), provider)
	_, err = explainer.Explain(context.Background(), domain.ExplainRequest{
		Path: "web/src/checkout.ts", Line: 4, Column: 15, Depth: "hover",
	})
	if err != nil {
		t.Fatalf("Explain() error = %v", err)
	}
	if len(provider.requests) != 1 {
		t.Fatalf("structured request count = %d, want 1", len(provider.requests))
	}
	request := provider.requests[0]
	if request.ReasoningEffort != "none" {
		t.Fatalf("hover reasoning effort = %q, want none", request.ReasoningEffort)
	}
	if request.MaxOutputTokens < 1400 {
		t.Fatalf("hover max output tokens = %d, want at least 1400 to avoid structured JSON truncation", request.MaxOutputTokens)
	}
}

func TestSeeMoreUsesExpandedOutputBudgetAndFiltersWeakInferences(t *testing.T) {
	if seeMoreMaxOutputTokens != 3000 {
		t.Fatalf("See More max tokens = %d, want 3000", seeMoreMaxOutputTokens)
	}
	filtered := confidentInferences([]aiout.Inference{
		{Text: "probably", Confidence: 0.49}, {Text: "supported", Confidence: 0.5},
	}, 0.5)
	if len(filtered) != 1 || filtered[0].Text != "supported" {
		t.Fatalf("weak inferences were not filtered: %+v", filtered)
	}
	if got := promptVersionForFeature(contextpack.FeatureSeeMore); got != "see-more-v3" {
		t.Fatalf("See More prompt version = %q", got)
	}
}

func TestExplainReturnsProviderErrorInsteadOfHeuristicMarkdown(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "internal/order/service.go", `package order

type Service struct{}
func (s *Service) Submit() {}
`)
	repository, err := repository.OpenJSON(filepath.Join(t.TempDir(), "index.json"))
	if err != nil {
		t.Fatal(err)
	}
	backgroundIndexer := indexer.New(root, 1_500_000, codeparser.New(), repository)
	if err := backgroundIndexer.Scan(context.Background()); err != nil {
		t.Fatalf("Scan() error = %v", err)
	}

	explainer := NewExplainer(repository, NewWorkspace(root), &capturingProvider{err: errors.New("LLM HTTP 503")})
	_, err = explainer.Explain(context.Background(), domain.ExplainRequest{
		Path:   "internal/order/service.go",
		Line:   4,
		Column: 10,
		Depth:  "hover",
	})
	if err == nil {
		t.Fatal("Explain() succeeded with a failing provider; want error")
	}
	appErr, ok := apperror.As(err)
	if !ok || appErr.Code != apperror.CodeProviderUnavailable {
		t.Fatalf("error = %v, want PROVIDER_UNAVAILABLE app error", err)
	}
	if appErr.Cause == nil || !strings.Contains(appErr.Cause.Error(), "LLM HTTP 503") {
		t.Fatalf("provider cause not preserved: %v", appErr.Cause)
	}
}

func TestExplanationResultAndEvidenceExposeBackendCodeSelection(t *testing.T) {
	t.Parallel()
	result := explanationResult(aiout.Explanation{SchemaVersion: aiout.ExplanationSchemaVersion, Summary: "x", CodeEvidenceIDs: []string{"ev:1"}})
	if len(result.CodeEvidenceIDs) != 1 || result.CodeEvidenceIDs[0] != "ev:1" {
		t.Fatalf("code selection not copied to DTO: %+v", result)
	}
	evidence := packEvidence([]contextpack.Evidence{{
		ID: "ev:1", Path: "main.go", DisplayCode: "func main() {}", DisplayLanguage: "go", DisplayCodeTruncated: true,
	}})
	if len(evidence) != 1 || evidence[0].Code != "func main() {}" || evidence[0].Language != "go" || !evidence[0].CodeTruncated {
		t.Fatalf("backend-owned code not copied to evidence DTO: %+v", evidence)
	}
}

func writeFile(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}
